[package]
build = "build.rs"
name = "rstm"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doc = true
doctest = false
test = true

# ********* [Package Metadata] *********
[package.metadata.docs.rs]
all-features = false
features = ["full"]
rustc-args = ["--cfg", "docsrs" ]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

# ********* [Dependencies] *********
[dependencies]
rstm-core = { workspace = true }

[dev-dependencies]
anyhow = { features = ["std"], workspace = true }
criterion = { features = ["plotters"], version = "0.7" }
lazy_static = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { features = ["json", "serde"], workspace = true }

[features]
default = ["std"]

full = [
  "default", 
  "macros", 
  "rand", 
  "serde", 
  "tracing"
]

# ********* [FF] Features *********
macros = []

nightly = [
  "rstm-core/nightly",
]

json = [
  "alloc",
  "rstm-core/json",
]

# ********* [FF] Environments *********
std = [
  "alloc", 
  "rstm-core/std"
]

wasi = [
  "rstm-core/wasi",
]

wasm = [
  "rstm-core/wasm",
]

# ************* [FF:Dependencies] *************

alloc = [
  "rstm-core/alloc",
]

rand = [
  "rstm-core/rand",
]

rng = [
  "rstm-core/rng",
]

serde = [
  "rstm-core/serde",
]

serde_json = [
  "rstm-core/serde_json",
]

tracing = [
  "rstm-core/tracing"
]

wasm_bindgen = [
  "rstm-core/wasm_bindgen",
]

# ************* [Benchmarks] *************
[[bench]]
harness = false
name = "default"
required-features = ["std"]

# ************* [Examples] *************
[[example]]
name = "actor"
required-features = ["alloc", "tracing"]

# ************* [Unit Tests] *************
[[test]]
name = "default"

[[test]]
name = "actors"
required-features = ["alloc", "macros"]

[[test]]
name = "macros"
required-features = ["alloc", "macros"]
