[package]
build = "build.rs"
name = "rstm"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = [ 
    "cdylib", 
    "rlib",
]
bench = true
doc = true
doctest = false
test = true

[package.metadata.docs.rs]
all-features = false
features = [ "full" ]
rustc-args = [ "--cfg", "docsrs" ]

[dependencies]
rstm-core = { workspace = true }

[dev-dependencies]
anyhow = { features = ["std"], workspace = true }
criterion = { features = ["plotters"], workspace = true }
lazy_static = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { features = ["json", "serde"], workspace = true }

[features]
default = [
    "std",
]

full = [
    "default",
    "rand",
    "serde",
    "tracing",
]

# ********* [FF] Dependencies *********
alloc = [
    "rstm-core/alloc",
]

anyhow = [
    "rstm-core/anyhow",
]

json = [
    "rstm-core/json",
]

rand = [
    "rstm-core/rand",
]

rng = [
    "rstm-core/rng",
]

serde = [
    "rstm-core/serde",
]

serde_json = [
    "rstm-core/serde_json",
]

tracing = [
    "rstm-core/tracing",
]

# ************* [FF:Environments] *************
std = [
    "alloc",
    "rstm-core/std",
]

wasi = [
    "rstm-core/wasi",
]

wasm = [
    "rstm-core/wasm",
]


# ************* [Benchmarks] *************
[[bench]]
name = "default"
required-features = [ "std" ]
harness = false

# ********* Examples *********
[[example]]
name = "actor"
required-features = [ "alloc", "tracing" ]
