[package]
name = "rstm"
authors.workspace = true
build = "build.rs"
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "alloc",
]

full = [
    "default",
    "serde",
    "tracing",
]

# ********* [FF] Dependencies *********
alloc = [
    "rstm-core/alloc",
    "serde?/alloc",
]

serde = [
    "dep:serde",
    "rstm-core/serde",
]

tracing = [
    "dep:tracing",
    "rstm-core/tracing",
]

# ********* [FF] Environments *********
std = [
    "alloc",
    "rstm-core/std",
    "serde?/std",
    "strum/std",
]

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = false
test = true

[[example]]
name = "actor"
required-features = ["alloc", "tracing"]

# ****************** Dependencies ******************
[dependencies]
thiserror.workspace = true

[dependencies.rstm-core]
default-features = false
path = "../core"
version = "0.0.4"

[dependencies.serde]
default-features = false
features = ["derive"]
optional = true
version = "1"

[dependencies.strum]
default-features = false
features = ["derive"]
version = "0.26"

[dependencies.tracing]
features = []
optional = true
version = "0.1"

# ****************** Dev Dependencies ******************
[dev-dependencies]
lazy_static.workspace = true
tracing-subscriber = "0.3"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
