[package]
build = "build.rs"
name = "rstm"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "std",
]

full = [
    "default",
    "rand",
    "serde",
    "tracing",
]

# ********* [FF] Dependencies *********
alloc = [
    "rstm-core/alloc",
]

json = [
    "rstm-core/json",
]

serde = [
    "rstm-core/serde",
]

rand = [
    "rstm-core/rand",
]

rng = [
    "rstm-core/rng",
]

tracing = [
    "rstm-core/tracing",
]

# ********* [FF] Environments *********
std = [
    "alloc",
    "rstm-core/std",
]

[lib]
bench = true
crate-type = [ "cdylib", "rlib" ]
doctest = false
test = true

[dependencies]
rstm-core = { path = "../core", version = "0.0.6" }

[dev-dependencies]
lazy_static = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { features = ["env-filter", "fmt", "json", "serde"], workspace = true }

[package.metadata.docs.rs]
all-features = true
rustc-args = [ "--cfg", "docsrs" ]

# ********* Examples *********
[[example]]
name = "actor"
required-features = [ "alloc", "tracing" ]
