[package]
name = "rstm"
authors.workspace = true
build = "build.rs"
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "std",
]

full = [
    "default",
    "serde",
    "tracing",
]

# [FF] Dependencies
alloc = [
    "serde?/alloc",
]

serde = [
    "dep:serde",
]

tracing = [
    "dep:tracing",
]

# ********* [FF] Environments *********
std = [
    "alloc",
    "serde?/std",
    "strum/std",
]

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = false
test = true

[[example]]
name = "default"
required-features = ["tracing"]

[dependencies]
thiserror = "1"

[dev-dependencies]
lazy_static = "1"
tracing-subscriber = { features = [], version = "0.3" }

[dependencies.serde]
default-features = false
features = ["derive"]
optional = true
version = "1"

[dependencies.strum]
default-features = false
features = ["derive"]
version = "0.26"

[dependencies.tracing]
features = []
optional = true
version = "0.1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
